version: '3'
services:
  discovery-server:
    build:
      context: ./
      dockerfile: ./discovery-server/Dockerfile
    ports:
      - '8761:8761'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8761
      - PROFILE=dev
  api-gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080
      - PROFILE=dev
    links:
      - discovery-server
    depends_on:
      - discovery-server
  db-v1-posts:
    image: postgres
    environment:
      POSTGRES_DB: "db-v1-posts"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
       - '15432:5432'
    links:
      - v1-posts
  db-admin-v1-posts:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "xpto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2020!"
    ports:
      - '16543:80'
    depends_on:
     - discovery-server
     - db-v1-posts
  v1-posts:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./posts/Dockerfile
    ports:
      - '8081:8081'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
      - PROFILE=dev
    links:
      - discovery-server
    depends_on:
      - discovery-server
  v1-users:
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    ports:
      - '8082:8082'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8082
      - PROFILE=dev
    links:
      - discovery-server
    depends_on:
      - discovery-server

